name: volcano_quest
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.3
  shared_preferences: ^2.5.5
  model_viewer_plus: ^1.10.0
  drift: ^2.33.0
  rive: ^0.14.6
  flame: ^1.37.0
  lottie: ^3.3.3
  flutter_animate: ^4.5.2
  just_audio: ^0.10.5
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
